/*
 * This source file was generated by the Gradle 'init' task
 */
package org.worker;

import org.worker.rest.WorkerController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private static String workerId;

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // Accept optional CLI args: [port] [workerId]
        // Examples:
        //   java -jar app.jar 8080 worker-1
        //   java -Dserver.port=8080 -Dworker.id=worker-1 -jar app.jar
        int port;
        if (args != null && args.length >= 1 && args[0] != null && !args[0].isEmpty()) {
            port = Integer.parseInt(args[0]);
        } else {
            port = Integer.parseInt(System.getProperty("server.port", "8080"));
        }
        for (String arg : args) {
            System.out.println("Arg: " + arg);
        }
        if (args != null && args.length >= 2 && args[1] != null) {
            workerId = args[1];
        } else {
            workerId = System.getProperty("worker.id", "");
        }

        System.out.println("Starting WorkerController on port=" + port + " workerId=" + workerId);

        WorkerController controller = new WorkerController();
        try {
            controller.start(port);
            System.out.println("WorkerController started on port " + port);

            // Ensure we stop the server cleanly on JVM shutdown
            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                System.out.println("Shutting down WorkerController...");
                controller.stop();
            }));

        } catch (Exception e) {
            System.err.println("Failed to start WorkerController: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    public static String getWorkerId() {
        return workerId;
    }
}
