/*
 * This source file was generated by the Gradle 'init' task
 */
package org.orchestrator;

import org.orchestrator.config.WorkerConfig;
import org.orchestrator.rest.EngineController;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Start the lightweight HTTP server that exposes the REST endpoints.
        System.out.println(new App().getGreeting());

        for (String arg : args) {
            WorkerConfig.addWorker(arg);
        }

        System.out.println("Printing worker config :: " + WorkerConfig.getWorkerPool().toString());

        try {
            EngineController controller = new EngineController();
            controller.start(9000);
            System.out.println("Press Ctrl+C to stop the server");

            Runtime.getRuntime().addShutdownHook(new Thread(() -> {
                System.out.println("Shutting down WorkerController...");
                controller.stop();
            }));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
